server:
  port: 8011
spring:
  rabbitmq:
    host: 192.168.80.128
    listener:
      simple:
        ## auto表示自动完成这次消费，manual表示需要手动告知完成消费
        acknowledge-mode: auto
        ## listener开几个线程处理数据
        concurrency: 5
        ## linstener 最大开几个线程
        max-concurrency: 10
        ## 一次拿几条数据
        prefetch: 1
    password: admin
    port: 5672
    username: admin
    virtual-host: my_vhost
